//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Packager.CI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Umbraco.Packager.CI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///                        888
        ///                        888
        ///888   888 88888b.d88b.  88888b.  888d888 8888b.   .d8888b  .d88b.
        ///888   888 888 &quot;888 &quot;88b 888 &quot;88b 888P&quot;      &quot;88b d88P&quot;    d88&quot;&quot;88b
        ///888   888 888  888  888 888  888 888    .d888888 888      888  888
        ///Y88   88Y 888  888  888 888 d88P 888    888  888 Y88b.    Y88..88P
        /// &quot;Y888P&quot;  888  888  888 88888P&quot;  888    &quot;Y888888  &quot;Y8888P  &quot;Y88P&quot;
        ///
        ///------------------------------------------------------------------
        ///    .
        /// </summary>
        internal static string Ascaii {
            get {
                return ResourceManager.GetString("Ascaii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information see ?? .
        /// </summary>
        internal static string HelpFooter {
            get {
                return ResourceManager.GetString("HelpFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Init_Author {
            get {
                return ResourceManager.GetString("Init.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package file saved.
        /// </summary>
        internal static string Init_Complete {
            get {
                return ResourceManager.GetString("Init.Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About to write to {0}.
        /// </summary>
        internal static string Init_Confirm {
            get {
                return ResourceManager.GetString("Init.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Init_Description {
            get {
                return ResourceManager.GetString("Init.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This utility will walk you through creating a package.xml file.
        ///It only covers the most common items, and trys to guess sensible defaults
        ///
        ///see ??? for definitive documentation of those fields and excatly what they do.
        /// </summary>
        internal static string Init_Header {
            get {
                return ResourceManager.GetString("Init.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Version: &apos;{0}&apos;.
        /// </summary>
        internal static string Init_InvalidVersion {
            get {
                return ResourceManager.GetString("Init.InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence.
        /// </summary>
        internal static string Init_Licence {
            get {
                return ResourceManager.GetString("Init.Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location &apos;{0}&apos; where you want to put the package file doesn&apos;t exist..
        /// </summary>
        internal static string Init_MissingFolder {
            get {
                return ResourceManager.GetString("Init.MissingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Name.
        /// </summary>
        internal static string Init_PackageName {
            get {
                return ResourceManager.GetString("Init.PackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It this OK?.
        /// </summary>
        internal static string Init_Prompt {
            get {
                return ResourceManager.GetString("Init.Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbraco Version.
        /// </summary>
        internal static string Init_UmbracoVersion {
            get {
                return ResourceManager.GetString("Init.UmbracoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string Init_Url {
            get {
                return ResourceManager.GetString("Init.Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Init_Version {
            get {
                return ResourceManager.GetString("Init.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Init_Website {
            get {
                return ResourceManager.GetString("Init.Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     - Adding Folder: {0}.
        /// </summary>
        internal static string Pack_AddingFolder {
            get {
                return ResourceManager.GetString("Pack.AddingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     - Adding: {0} to {1}.
        /// </summary>
        internal static string Pack_AddingSingle {
            get {
                return ResourceManager.GetString("Pack.AddingSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Adding files to package.
        /// </summary>
        internal static string Pack_AddPackageFiles {
            get {
                return ResourceManager.GetString("Pack.AddPackageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building package from package from package.xml.
        /// </summary>
        internal static string Pack_BuildingFile {
            get {
                return ResourceManager.GetString("Pack.BuildingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building package from folder: {0}.
        /// </summary>
        internal static string Pack_BuildingFolder {
            get {
                return ResourceManager.GetString("Pack.BuildingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Building package.
        /// </summary>
        internal static string Pack_BuildPackage {
            get {
                return ResourceManager.GetString("Pack.BuildPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Pack_Complete {
            get {
                return ResourceManager.GetString("Pack.Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Directory {0} doesn&apos;t exist.
        /// </summary>
        internal static string Pack_DirectoryMissing {
            get {
                return ResourceManager.GetString("Pack.DirectoryMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Getting Package Name.
        /// </summary>
        internal static string Pack_GetPackageName {
            get {
                return ResourceManager.GetString("Pack.GetPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Loading Package File: {0}.
        /// </summary>
        internal static string Pack_LoadingFile {
            get {
                return ResourceManager.GetString("Pack.LoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the package.xml file {0}.
        /// </summary>
        internal static string Pack_MissingXml {
            get {
                return ResourceManager.GetString("Pack.MissingXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Saving Package to {0}.
        /// </summary>
        internal static string Pack_SavingPackage {
            get {
                return ResourceManager.GetString("Pack.SavingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Updating package version.
        /// </summary>
        internal static string Pack_UpdatingVersion {
            get {
                return ResourceManager.GetString("Pack.UpdatingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Key is invalid.
        /// </summary>
        internal static string Push_ApiKeyInvalid {
            get {
                return ResourceManager.GetString("Push.ApiKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package &apos;{0}&apos; was sucessfully uploaded to our.umbraco.com.
        /// </summary>
        internal static string Push_Complete {
            get {
                return ResourceManager.GetString("Push.Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting info form package.xml file.
        /// </summary>
        internal static string Push_Extracting {
            get {
                return ResourceManager.GetString("Push.Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbraco package file &apos;{0}&apos; must be a .zip.
        /// </summary>
        internal static string Push_FileNotZip {
            get {
                return ResourceManager.GetString("Push.FileNotZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid package.xml.
        /// </summary>
        internal static string Push_InvalidXml {
            get {
                return ResourceManager.GetString("Push.InvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find file {0}.
        /// </summary>
        internal static string Push_MissingFile {
            get {
                return ResourceManager.GetString("Push.MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find //umbPackage/info/package in XML.
        /// </summary>
        internal static string Push_MissingPackageNode {
            get {
                return ResourceManager.GetString("Push.MissingPackageNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbraco package file &apos;{0}&apos; does not contain a package.xml file.
        /// </summary>
        internal static string Push_NoPackageXml {
            get {
                return ResourceManager.GetString("Push.NoPackageXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A package file named &apos;{0}&apos; already exists for this package.
        /// </summary>
        internal static string Push_PackageExists {
            get {
                return ResourceManager.GetString("Push.PackageExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading {0} to our.umbraco.com ....
        /// </summary>
        internal static string Push_Uploading {
            get {
                return ResourceManager.GetString("Push.Uploading", resourceCulture);
            }
        }
    }
}
