//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Packager.CI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Umbraco.Packager.CI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///                        888
        ///                        888
        ///888   888 88888b.d88b.  88888b.  888d888 8888b.   .d8888b  .d88b.
        ///888   888 888 &quot;888 &quot;88b 888 &quot;88b 888P&quot;      &quot;88b d88P&quot;    d88&quot;&quot;88b
        ///888   888 888  888  888 888  888 888    .d888888 888      888  888
        ///Y88   88Y 888  888  888 888 d88P 888    888  888 Y88b.    Y88..88P
        /// &quot;Y888P&quot;  888  888  888 88888P&quot;  888    &quot;Y888888  &quot;Y8888P  &quot;Y88P&quot;
        ///
        ///------------------------------------------------------------------
        ///    .
        /// </summary>
        internal static string Ascaii {
            get {
                return ResourceManager.GetString("Ascaii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This utility will walk you through creating a package.xml file.
        ///It only covers the most common items, and trys to guess sensible defaults
        ///
        ///see .. for definitive documentatio of those fields
        ///and excatly what they do.
        /// </summary>
        internal static string InitHeader {
            get {
                return ResourceManager.GetString("InitHeader", resourceCulture);
            }
        }
    }
}
